# Copyright 2025 Erik Lönroth
# See LICENSE file for licensing details.

[tox]
no_package = True
skip_missing_interpreters = True
env_list = format, lint, static, unit
min_version = 4.0.0

[testenv]
allowlist_externals = uv
set_env =
    PYTHONPATH = {tox_root}/lib:{tox_root}/src
    PYTHONBREAKPOINT=pdb.set_trace
    PY_COLORS=1
pass_env =
    PYTHONPATH
    CHARM_BUILD_DIR
    MODEL_SETTINGS

[testenv:format]
description = Apply coding style standards to code
commands =
    uv run ruff format src tests
    uv run ruff check --fix src tests

[testenv:lint]
description = Check code against coding style standards
commands =
    uv run codespell {tox_root}
    uv run ruff check src tests
    uv run ruff format --check --diff src tests

[testenv:unit]
description = Run unit tests
commands =
    uv run coverage run --source=src \
                 -m pytest \
                 --tb native \
                 -v \
                 -s \
                 {posargs} \
                 tests/unit
    uv run coverage report

[testenv:static]
description = Run static type checks
commands =
    uv run pyright {posargs}

[testenv:integration]
description = Run integration tests
commands =
    uv run pytest -v \
           -s \
           --tb native \
           --log-cli-level=INFO \
           {posargs} \
           tests/integration
