# Copyright 2025 Erik Lönroth
# See LICENSE file for licensing details.

"""Workload management helpers for Grafana Alloy.

This module is intentionally free of charm/ops dependencies so it can be
unit-tested in isolation, mirroring the loki-vm structure.
"""

from __future__ import annotations

import logging
import os
import pwd
import re
import shutil
import subprocess
import time
from pathlib import Path
from typing import Iterable

from config_builder import (
    DEFAULT_CONFIG_BACKUP_PATH,
    DEFAULT_CONFIG_PATH,
    DEFAULT_PACKAGE_CONFIG_BACKUP_PATH,
)

logger = logging.getLogger(__name__)

GENERATED_CONFIG_HEADER = (
    "// This file is generated by Juju. Manual changes will be overwritten.\n"
    "// Adjust charm config to update this file.\n"
)
_GENERATED_HEADER_PREFIX = "// This file is generated by Juju."

GRAFANA_APT_SOURCE = (
    "deb [signed-by=/etc/apt/keyrings/grafana.gpg] https://apt.grafana.com stable main"
)
GRAFANA_GPG_KEY_URL = "https://apt.grafana.com/gpg.key"

DEFAULT_START_TIMEOUT = 60
DEFAULT_VERIFY_TIMEOUT = 30
DEFAULT_STATUS_TIMEOUT = 10
DEFAULT_SYSTEMD_DEFAULTS_PATH = "/etc/default/alloy"


def _run(cmd: Iterable[str], *, timeout: int | None = None) -> subprocess.CompletedProcess[str]:
    """Run a command and return the completed process."""
    logger.debug("Running command: %s", " ".join(cmd))
    env = {**os.environ, "DEBIAN_FRONTEND": "noninteractive"}
    return subprocess.run(
        list(cmd),
        check=True,
        text=True,
        capture_output=True,
        timeout=timeout,
        env=env,
    )


def _run_shell(cmd: str, *, timeout: int | None = None) -> subprocess.CompletedProcess[str]:
    """Run a shell command (used only for pipeline commands)."""
    logger.debug("Running shell command: %s", cmd)
    env = {**os.environ, "DEBIAN_FRONTEND": "noninteractive"}
    return subprocess.run(
        cmd,
        check=True,
        text=True,
        capture_output=True,
        timeout=timeout,
        env=env,
        shell=True,
    )


def _systemctl(*args: str) -> None:
    """Run a systemctl command."""
    _run(["systemctl", *args])


def _wait_for_active(service: str, *, timeout: int = DEFAULT_START_TIMEOUT) -> None:
    """Wait for a systemd service to become active."""
    deadline = time.time() + timeout
    while time.time() < deadline:
        try:
            _run(["systemctl", "is-active", "--quiet", service])
            return
        except subprocess.CalledProcessError:
            time.sleep(1)
    raise RuntimeError(f"Service {service} did not become active within {timeout} seconds")


# Workload lifecycle


def install() -> None:
    """Install the workload using the official Grafana APT repository."""
    _run(["apt-get", "update"])
    _run(["apt-get", "install", "-y", "wget", "gpg"])
    _run(["mkdir", "-p", "/etc/apt/keyrings"])
    _run_shell(
        f"wget -q -O - {GRAFANA_GPG_KEY_URL} | gpg --dearmor > /etc/apt/keyrings/grafana.gpg"
    )
    _run_shell(f'echo "{GRAFANA_APT_SOURCE}" | tee /etc/apt/sources.list.d/grafana.list')
    _run(["apt-get", "update"])
    _run(["apt-get", "install", "-y", "alloy"])


def start() -> None:
    """Start the workload."""
    _systemctl("enable", "--now", "alloy")
    _wait_for_active("alloy")


def stop() -> None:
    """Stop the workload."""
    _systemctl("stop", "alloy")


def restart() -> None:
    """Restart the workload, recovering from systemd start-rate limiting if needed."""
    try:
        _systemctl("restart", "alloy")
    except subprocess.CalledProcessError:
        _systemctl("reset-failed", "alloy")
        _systemctl("start", "alloy")
    _wait_for_active("alloy")


def reload() -> None:
    """Reload the workload."""
    _systemctl("reload", "alloy")


def get_version() -> str | None:
    """Get the installed Alloy version."""
    try:
        result = _run(["alloy", "--version"])
    except (subprocess.CalledProcessError, FileNotFoundError):
        return None
    output = f"{result.stdout}\n{result.stderr}".strip()
    match = re.search(
        r"\bversion\s+v?([0-9]+(?:\.[0-9]+){1,3}(?:[-+][0-9A-Za-z.-]+)?)\b",
        output,
        flags=re.IGNORECASE,
    )
    if match:
        return match.group(1)
    fallback = re.search(
        r"\bv?([0-9]+(?:\.[0-9]+){1,3}(?:[-+][0-9A-Za-z.-]+)?)\b",
        output,
    )
    return fallback.group(1) if fallback else None


def verify_config(*, config_path: Path, timeout: int = DEFAULT_VERIFY_TIMEOUT) -> None:
    """Validate the Alloy configuration using `alloy fmt`."""
    _run(["alloy", "fmt", str(config_path)], timeout=timeout)


def is_active(*, timeout: int = DEFAULT_STATUS_TIMEOUT) -> bool:
    """Return True if the Alloy systemd service is active."""
    try:
        _run(["systemctl", "is-active", "--quiet", "alloy"], timeout=timeout)
        return True
    except (subprocess.CalledProcessError, FileNotFoundError):
        return False


def read_custom_args(*, defaults_path: Path = Path(DEFAULT_SYSTEMD_DEFAULTS_PATH)) -> str | None:
    """Read CUSTOM_ARGS from /etc/default/alloy."""
    try:
        content = defaults_path.read_text(encoding="utf-8")
    except FileNotFoundError:
        return None
    except OSError as exc:
        logger.warning("Failed to read %s: %s", defaults_path, exc)
        return None
    for line in content.splitlines():
        if line.strip().startswith("CUSTOM_ARGS="):
            value = line.split("=", 1)[1].strip()
            return _strip_quotes(value)
    return None


def write_custom_args(
    custom_args: str | None,
    *,
    defaults_path: Path = Path(DEFAULT_SYSTEMD_DEFAULTS_PATH),
) -> None:
    """Write CUSTOM_ARGS to /etc/default/alloy, preserving other settings."""
    lines: list[str] = []
    existing = False
    if defaults_path.exists():
        try:
            lines = defaults_path.read_text(encoding="utf-8").splitlines()
        except OSError as exc:
            logger.warning("Failed to read %s: %s", defaults_path, exc)
            lines = []
    updated: list[str] = []
    for line in lines:
        if line.strip().startswith("CUSTOM_ARGS="):
            existing = True
            if custom_args is not None:
                updated.append(_format_custom_args(custom_args))
            continue
        updated.append(line)
    if not existing and custom_args is not None:
        updated.append(_format_custom_args(custom_args))
    if not updated and custom_args is None and not defaults_path.exists():
        return
    defaults_path.parent.mkdir(parents=True, exist_ok=True)
    _write_file_atomic(defaults_path, "\n".join(updated).rstrip() + "\n")


# Config file helpers


def write_config_text(
    config_text: str,
    *,
    config_path: Path = Path(DEFAULT_CONFIG_PATH),
    backup_path: Path = Path(DEFAULT_CONFIG_BACKUP_PATH),
) -> None:
    """Write Alloy configuration text to disk and persist a backup copy."""
    _write_file_atomic(config_path, config_text)
    _write_file_atomic(backup_path, config_text)


def preserve_default_config(
    *,
    config_path: Path = Path(DEFAULT_CONFIG_PATH),
    preserved_path: Path = Path(DEFAULT_PACKAGE_CONFIG_BACKUP_PATH),
) -> None:
    """Preserve the package default config file if it exists."""
    if not config_path.exists():
        return
    if _has_generated_header(config_path):
        logger.warning("Package default config already replaced by generated config.")
        return
    if preserved_path.exists():
        if _has_generated_header(preserved_path):
            shutil.copy2(config_path, preserved_path)
        return
    preserved_path.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(config_path, preserved_path)


def ensure_config_dir_permissions(config_dir: str) -> None:
    """Ensure Alloy can write to the configuration directory (root-only helper)."""
    if os.geteuid() != 0:
        return
    _ensure_alloy_permissions(Path(config_dir))


def _ensure_alloy_permissions(target: Path) -> None:
    """Ensure Alloy can write to its directories."""
    ids = _alloy_ids()
    if ids is None:
        return
    uid, gid = ids
    _ensure_dir(target, uid, gid)
    _chown_tree(target, uid, gid)


def _ensure_dir(path: Path, uid: int, gid: int) -> None:
    path.mkdir(parents=True, exist_ok=True)
    try:
        os.chown(path, uid, gid)
    except PermissionError:
        logger.debug("Skipping chown for %s (insufficient permissions)", path)


def _chown_tree(path: Path, uid: int, gid: int) -> None:
    """Recursively chown a directory tree, ignoring permission errors."""
    try:
        os.chown(path, uid, gid)
    except PermissionError:
        logger.debug("Skipping chown for %s (insufficient permissions)", path)
        return
    for root, dirs, files in os.walk(path):
        for name in dirs:
            try:
                os.chown(os.path.join(root, name), uid, gid)
            except PermissionError:
                logger.debug("Skipping chown for %s", os.path.join(root, name))
        for name in files:
            try:
                os.chown(os.path.join(root, name), uid, gid)
            except PermissionError:
                logger.debug("Skipping chown for %s", os.path.join(root, name))


def _alloy_ids() -> tuple[int, int] | None:
    """Return (uid, gid) for alloy user/group, or None if missing."""
    try:
        entry = pwd.getpwnam("alloy")
        return entry.pw_uid, entry.pw_gid
    except KeyError:
        logger.warning("User/group 'alloy' not found; skipping ownership update.")
        return None


def _has_generated_header(path: Path) -> bool:
    """Return True if the file starts with the Juju-generated header."""
    try:
        with path.open("r", encoding="utf-8") as handle:
            first_line = handle.readline().strip()
        return first_line.startswith(_GENERATED_HEADER_PREFIX)
    except OSError:
        return False


def _write_file_atomic(path: Path, content: str) -> None:
    """Write file atomically to avoid partial writes."""
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp_path = path.with_suffix(f"{path.suffix}.tmp")
    tmp_path.write_text(content)
    tmp_path.replace(path)


def _format_custom_args(value: str) -> str:
    """Format a CUSTOM_ARGS line for /etc/default/alloy."""
    return f'CUSTOM_ARGS="{value}"'


def _strip_quotes(value: str) -> str:
    """Strip a single layer of surrounding quotes from a value."""
    if value.startswith('"') and value.endswith('"'):
        return value[1:-1]
    if value.startswith("'") and value.endswith("'"):
        return value[1:-1]
    return value
